# Form implementation generated from reading ui file 'c:\Users\Gebruiker\Documents\GitHub\Python-Module-Week7\ui\admin_panel.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_InterviewsWindow(object):
    def setupUi(self, InterviewsWindow):
        InterviewsWindow.setObjectName("InterviewsWindow")
        InterviewsWindow.resize(530, 480)
        InterviewsWindow.setMinimumSize(QtCore.QSize(512, 480))
        InterviewsWindow.setMaximumSize(QtCore.QSize(530, 16777215))
        InterviewsWindow.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(InterviewsWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=InterviewsWindow)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #ab94da;\n"
"    border: none;\n"
"    border-radius: 20 px;\n"
"}\n"
"\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setMaximumSize(QtCore.QSize(110, 30))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\Gebruiker\\Documents\\GitHub\\Python-Module-Week7\\ui\\../resorces/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.titleLabel = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_5.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(110, 30, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setObjectName("searchLayout")
        self.activityButton = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activityButton.sizePolicy().hasHeightForWidth())
        self.activityButton.setSizePolicy(sizePolicy)
        self.activityButton.setBaseSize(QtCore.QSize(0, 0))
        self.activityButton.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #6f56b0;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8263c6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #594097;\n"
"}\n"
"")
        self.activityButton.setObjectName("activityButton")
        self.searchLayout.addWidget(self.activityButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.searchLayout.addItem(spacerItem1)
        self.emailButton = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emailButton.sizePolicy().hasHeightForWidth())
        self.emailButton.setSizePolicy(sizePolicy)
        self.emailButton.setStyleSheet("QPushButton {\n"
"    background-color: #6f56b0;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8263c6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #594097;\n"
"}\n"
"")
        self.emailButton.setObjectName("emailButton")
        self.searchLayout.addWidget(self.emailButton)
        self.verticalLayout_3.addLayout(self.searchLayout)
        self.activityTable = QtWidgets.QTableWidget(parent=self.frame)
        self.activityTable.setEnabled(True)
        self.activityTable.setMinimumSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 208, 245))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 208, 245))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 208, 245))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 208, 245))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 208, 245))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 208, 245))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 208, 245))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 208, 245))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 208, 245))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        self.activityTable.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        self.activityTable.setFont(font)
        self.activityTable.setAutoFillBackground(False)
        self.activityTable.setStyleSheet("QHeaderView::section {\n"
"    background-color: #6f56b0;     /* Başlık hücrelerinin arka planı */\n"
"    color: white;                  /* Başlık yazısı */\n"
"    font-weight: bold;\n"
"\n"
"    border: 1px solid #a085b4;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: #e6d0f5;  /* Hücrelerin arka planı */\n"
"    color: black;               /* Yazı rengi */\n"
"    gridline-color: #b58cd9;    /* Hücre çizgi rengi */\n"
"    alternate-background-color: #f9f9f9;    \n"
"    font-size: 13px;\n"
"    selection-background-color: #00aaff;\n"
"    selection-color: black;\n"
"    border-radius: 0px;\n"
"    border: none;\n"
"}\n"
"")
        self.activityTable.setObjectName("activityTable")
        self.activityTable.setColumnCount(4)
        self.activityTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.activityTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.activityTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.activityTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.activityTable.setHorizontalHeaderItem(3, item)
        self.activityTable.horizontalHeader().setDefaultSectionSize(116)
        self.verticalLayout_3.addWidget(self.activityTable)
        self.bottomLayout = QtWidgets.QHBoxLayout()
        self.bottomLayout.setObjectName("bottomLayout")
        self.returnButton = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.returnButton.sizePolicy().hasHeightForWidth())
        self.returnButton.setSizePolicy(sizePolicy)
        self.returnButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.returnButton.setStyleSheet("QPushButton {\n"
"    background-color: #6f56b0;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8263c6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #594097;\n"
"}\n"
"")
        self.returnButton.setObjectName("returnButton")
        self.bottomLayout.addWidget(self.returnButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.bottomLayout.addItem(spacerItem2)
        self.exitButton = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitButton.sizePolicy().hasHeightForWidth())
        self.exitButton.setSizePolicy(sizePolicy)
        self.exitButton.setMinimumSize(QtCore.QSize(80, 0))
        self.exitButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.exitButton.setStyleSheet("QPushButton {\n"
"    background-color: #6f56b0;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8263c6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #594097;\n"
"}\n"
"")
        self.exitButton.setObjectName("exitButton")
        self.bottomLayout.addWidget(self.exitButton)
        self.verticalLayout_3.addLayout(self.bottomLayout)
        self.verticalLayout_3.setStretch(0, 10)
        self.verticalLayout_3.setStretch(1, 5)
        self.verticalLayout_3.setStretch(2, 80)
        self.verticalLayout_3.setStretch(3, 5)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(InterviewsWindow)
        QtCore.QMetaObject.connectSlotsByName(InterviewsWindow)

    def retranslateUi(self, InterviewsWindow):
        _translate = QtCore.QCoreApplication.translate
        InterviewsWindow.setWindowTitle(_translate("InterviewsWindow", "Interviews Window"))
        self.titleLabel.setText(_translate("InterviewsWindow", "Admin Panel"))
        self.activityButton.setText(_translate("InterviewsWindow", "Display Events"))
        self.emailButton.setText(_translate("InterviewsWindow", "Send E-mail"))
        item = self.activityTable.horizontalHeaderItem(0)
        item.setText(_translate("InterviewsWindow", "Event Name"))
        item = self.activityTable.horizontalHeaderItem(1)
        item.setText(_translate("InterviewsWindow", "Start Time"))
        item = self.activityTable.horizontalHeaderItem(2)
        item.setText(_translate("InterviewsWindow", "Participant Email"))
        item = self.activityTable.horizontalHeaderItem(3)
        item.setText(_translate("InterviewsWindow", "Organizer Email"))
        self.returnButton.setText(_translate("InterviewsWindow", "Back to Preferences"))
        self.exitButton.setText(_translate("InterviewsWindow", "Exit"))
