# Form implementation generated from reading ui file 'c:\Users\Gebruiker\Documents\GitHub\Python-Module-Week7\ui\applications.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(978, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(978, 549))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(10000, 10000))
        self.frame.setStyleSheet("QPushButton {\n"
"    background-color: #e2ab20;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;  /* Hover efekti */\n"
"    color: rgb(0,0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 132, 24);  /* Basılınca renk değişimi */\n"
"}\n"
"\n"
"\n"
"/* QLabel (Logo ve başlıklar için) */\n"
"QLabel {\n"
"    background-color: transparent;  /* Tam şeffaf */\n"
"    color: rgb(31, 113, 186);\n"
"    font-weight: bold; \n"
"    font-size: 25px;             /* Yazı büyük – butonu dolduracak gibi */\n"
"}\n"
"\n"
"/* QLineEdit */\n"
"QLineEdit {\n"
"    background-color: rgb(255, 251, 211); /* Ana rengin beyaza çok yakın tonu */\n"
"    border: 1px solid rgb(162, 189, 152);\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"    color: #000000;\n"
"}\n"
"\n"
"/* QTableWidget veya QTableView */\n"
"QTableWidget, QTableView {\n"
"    background-color: #eaf6fb; /* veya örnek: #f0f0f0 (açık gri) */\n"
"    color: black;\n"
"    gridline-color: #005f86;\n"
"    alternate-background-color: #f9f9f9;    \n"
"    border: 1px solid #079af5;\n"
"    selection-background-color: #00aaff;\n"
"    selection-color: black;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"/* Tablo başlık alanları */\n"
"QTableWidget QTableCornerButton::section,\n"
"QHeaderView::section {\n"
"    background-color: #079af5; /* Header daha açık deniz mavisi */\n"
"    color: white;\n"
"    font-weight: bold; \n"
"    padding: 2px;\n"
"}\n"
"\n"
"\n"
"\n"
"/* Frame */\n"
"QFrame {\n"
"    background-color: rgb(255, 212, 41);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"/* Scrollbar (isteğe bağlı) */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background: #003f5c;\n"
"    width: 10px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background: #005f86;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_label = QtWidgets.QLabel(parent=self.frame)
        self.logo_label.setMaximumSize(QtCore.QSize(110, 30))
        self.logo_label.setStyleSheet("")
        self.logo_label.setText("")
        self.logo_label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.logo_label.setPixmap(QtGui.QPixmap("c:\\Users\\Gebruiker\\Documents\\GitHub\\Python-Module-Week7\\ui\\../resorces/logo.png"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")
        self.horizontalLayout.addWidget(self.logo_label)
        self.title_label = QtWidgets.QLabel(parent=self.frame)
        self.title_label.setBaseSize(QtCore.QSize(0, 0))
        self.title_label.setStyleSheet("font: 75 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);")
        self.title_label.setObjectName("title_label")
        self.horizontalLayout.addWidget(self.title_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(110, 30, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.search_edit = QtWidgets.QLineEdit(parent=self.frame)
        self.search_edit.setEnabled(True)
        self.search_edit.setMinimumSize(QtCore.QSize(100, 30))
        self.search_edit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:0, stop:0 rgba(255, 222, 99, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: italic 8pt \"Arial\";\n"
"")
        self.search_edit.setText("")
        self.search_edit.setMaxLength(32768)
        self.search_edit.setObjectName("search_edit")
        self.horizontalLayout_4.addWidget(self.search_edit)
        self.search_button = QtWidgets.QPushButton(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.search_button.setFont(font)
        self.search_button.setAutoFillBackground(False)
        self.search_button.setStyleSheet("    border-radius: 8px;\n"
"    padding: 8px;")
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_4.addWidget(self.search_button)
        self.horizontalLayout_4.setStretch(0, 30)
        self.horizontalLayout_4.setStretch(1, 10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_allaplication = QtWidgets.QPushButton(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_allaplication.setFont(font)
        self.pushButton_allaplication.setAutoFillBackground(False)
        self.pushButton_allaplication.setStyleSheet("    border-radius: 8px;\n"
"    padding: 8px;")
        self.pushButton_allaplication.setObjectName("pushButton_allaplication")
        self.horizontalLayout_2.addWidget(self.pushButton_allaplication)
        self.pushButton_mentormeetingdefined = QtWidgets.QPushButton(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_mentormeetingdefined.setFont(font)
        self.pushButton_mentormeetingdefined.setAutoFillBackground(False)
        self.pushButton_mentormeetingdefined.setStyleSheet("    border-radius: 8px;\n"
"    padding: 8px;")
        self.pushButton_mentormeetingdefined.setObjectName("pushButton_mentormeetingdefined")
        self.horizontalLayout_2.addWidget(self.pushButton_mentormeetingdefined)
        self.pushButton_mentormeetinundefined = QtWidgets.QPushButton(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_mentormeetinundefined.setFont(font)
        self.pushButton_mentormeetinundefined.setAutoFillBackground(False)
        self.pushButton_mentormeetinundefined.setStyleSheet("    border-radius: 8px;\n"
"    padding: 8px;")
        self.pushButton_mentormeetinundefined.setObjectName("pushButton_mentormeetinundefined")
        self.horizontalLayout_2.addWidget(self.pushButton_mentormeetinundefined)
        self.comboBox = QtWidgets.QComboBox(parent=self.frame)
        self.comboBox.setStyleSheet("    border-radius: 8px;\n"
"    padding: 5px;")
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tableWidget_application = QtWidgets.QTableWidget(parent=self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        gradient = QtGui.QLinearGradient(1.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 222, 99))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        gradient = QtGui.QLinearGradient(1.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 222, 99))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        gradient = QtGui.QLinearGradient(1.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 222, 99))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        gradient = QtGui.QLinearGradient(1.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 222, 99))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        gradient = QtGui.QLinearGradient(1.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 222, 99))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        gradient = QtGui.QLinearGradient(1.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 222, 99))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        gradient = QtGui.QLinearGradient(1.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 222, 99))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        gradient = QtGui.QLinearGradient(1.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 222, 99))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        gradient = QtGui.QLinearGradient(1.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 222, 99))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.AlternateBase, brush)
        self.tableWidget_application.setPalette(palette)
        self.tableWidget_application.setStyleSheet("QHeaderView::section {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(252, 219, 28, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:0, stop:0 rgba(226, 171, 32, 255), stop:1 rgba(255, 255, 255, 255));;\n"
"    font-weight: bold;\n"
"    color: black;\n"
"    border: 1px solid #4CAF50;\n"
"    padding: 4px;\n"
"    \n"
"}\n"
"QTableWidget {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:0, stop:0 rgba(255, 222, 99, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"    }\n"
"QTableCornerButton::section {\n"
"    background-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:0, stop:0 rgba(226, 171, 32, 255), stop:1 rgba(255, 255, 255, 255));;\n"
"\n"
"    border: 1px solid #aaaaaa;\n"
"}\n"
"\n"
"")
        self.tableWidget_application.setRowCount(11)
        self.tableWidget_application.setColumnCount(7)
        self.tableWidget_application.setObjectName("tableWidget_application")
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        item.setForeground(brush)
        self.tableWidget_application.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_application.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_application.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_application.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_application.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_application.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_application.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_application.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_application.setItem(0, 1, item)
        self.tableWidget_application.horizontalHeader().setVisible(True)
        self.tableWidget_application.horizontalHeader().setDefaultSectionSize(114)
        self.tableWidget_application.horizontalHeader().setHighlightSections(False)
        self.tableWidget_application.verticalHeader().setDefaultSectionSize(45)
        self.verticalLayout_2.addWidget(self.tableWidget_application)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_backmenu = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_backmenu.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_backmenu.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_backmenu.setFont(font)
        self.pushButton_backmenu.setAutoFillBackground(False)
        self.pushButton_backmenu.setStyleSheet("    border-radius: 8px;\n"
"    padding: 8px;")
        self.pushButton_backmenu.setObjectName("pushButton_backmenu")
        self.horizontalLayout_3.addWidget(self.pushButton_backmenu)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_exit = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_exit.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_exit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setAutoFillBackground(False)
        self.pushButton_exit.setStyleSheet("    border-radius: 8px;\n"
"    padding: 8px;")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.horizontalLayout_3.addWidget(self.pushButton_exit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 978, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "Applications"))
        self.search_edit.setPlaceholderText(_translate("MainWindow", "Search"))
        self.search_button.setText(_translate("MainWindow", "SEARCH"))
        self.pushButton_allaplication.setText(_translate("MainWindow", "All Application"))
        self.pushButton_mentormeetingdefined.setText(_translate("MainWindow", "Mentor Meeting Defined"))
        self.pushButton_mentormeetinundefined.setText(_translate("MainWindow", "Mentor Meeting Undefined"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Prev Vit Check"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Filtered Applications"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Different Applications"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Duplicate Applications"))
        item = self.tableWidget_application.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_application.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name/Surname"))
        item = self.tableWidget_application.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mail"))
        item = self.tableWidget_application.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Telephone"))
        item = self.tableWidget_application.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Postcode"))
        item = self.tableWidget_application.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "State"))
        item = self.tableWidget_application.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Status"))
        __sortingEnabled = self.tableWidget_application.isSortingEnabled()
        self.tableWidget_application.setSortingEnabled(False)
        self.tableWidget_application.setSortingEnabled(__sortingEnabled)
        self.pushButton_backmenu.setText(_translate("MainWindow", "🔙 Back to Preferences"))
        self.pushButton_exit.setText(_translate("MainWindow", "❌ Exit"))
