# Form implementation generated from reading ui file 'c:\Users\Gebruiker\Documents\GitHub\Python-Module-Week7\ui\mentor.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 614)
        MainWindow.setStyleSheet("background-color: rgb(88, 185, 245);border-radius: 8px;\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setEnabled(True)
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setStyleSheet("/* Genel çerçeve */\n"
"\n"
"QWidget {\n"
"    background-color: #079af5; /* Deniz mavisi koyu ton */    \n"
"}\n"
"\n"
"/* QLabel (Logo ve başlıklar için) */\n"
"QLabel {\n"
"    background-color: transparent;  /* Tam şeffaf */\n"
"    color: rgb(31, 113, 186);\n"
"    font-weight: bold; \n"
"    font-size: 25px;             /* Yazı büyük – butonu dolduracak gibi */\n"
"}\n"
"\n"
"/* QPushButton */\n"
"QPushButton {\n"
"    background-color: #079af5; /* Widget arka planından biraz daha açık deniz mavisi */\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #007ab8; /* Hover için biraz daha parlak */\n"
"    color: rgb(0, 0, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004a68; /* Basılı halde koyu ton */\n"
"}\n"
"\n"
"/* QLineEdit */\n"
"QLineEdit {\n"
"    background-color: #eaf6fb; /* Ana rengin beyaza çok yakın tonu */\n"
"    border: 1px solid #079af5;\n"
"    border-radius: 4px;\n"
"    padding: 4px 8px;\n"
"    color: #000000;\n"
"}\n"
"\n"
"/* QComboBox */\n"
"QComboBox {\n"
"    background-color: #eaf6fb; /* Textbox ile aynı */ \n"
"    color: #000000;\n"
"    border: 1px solid #079af5;\n"
"    padding: 4px 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left: 1px solid #005f86;\n"
"}\n"
"\n"
"\n"
"\n"
"/* QTableWidget veya QTableView */\n"
"QTableWidget, QTableView {\n"
"    background-color: #eaf6fb; /* veya örnek: #f0f0f0 (açık gri) */\n"
"    color: black;\n"
"    gridline-color: #005f86;\n"
"    alternate-background-color: #f9f9f9;    \n"
"    border: 1px solid #079af5;\n"
"    selection-background-color: #00aaff;\n"
"    selection-color: black;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"/* Tablo başlık alanları */\n"
"QTableWidget QTableCornerButton::section,\n"
"QHeaderView::section {\n"
"    background-color: #079af5; /* Header daha açık deniz mavisi */\n"
"    color: white;\n"
"    font-weight: bold; \n"
"    padding: 2px;\n"
"}\n"
"\n"
"\n"
"\n"
"/* Frame */\n"
"QFrame {\n"
"    background-color: #58b9f5; /* Belirgin, orta açık deniz mavisi */\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"/* Scrollbar (isteğe bağlı) */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background: #003f5c;\n"
"    width: 10px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background: #005f86;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.logo_label = QtWidgets.QLabel(parent=self.frame_2)
        self.logo_label.setMaximumSize(QtCore.QSize(110, 30))
        self.logo_label.setStyleSheet("")
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("c:\\Users\\Gebruiker\\Documents\\GitHub\\Python-Module-Week7\\ui\\../resorces/logo.png"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")
        self.horizontalLayout_5.addWidget(self.logo_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.title_label = QtWidgets.QLabel(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_label.sizePolicy().hasHeightForWidth())
        self.title_label.setSizePolicy(sizePolicy)
        self.title_label.setStyleSheet("")
        self.title_label.setScaledContents(False)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout_5.addWidget(self.title_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(110, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.search_edit = QtWidgets.QLineEdit(parent=self.frame_2)
        self.search_edit.setObjectName("search_edit")
        self.horizontalLayout_4.addWidget(self.search_edit)
        self.search_button = QtWidgets.QPushButton(parent=self.frame_2)
        self.search_button.setStyleSheet("    border-radius: 8px;\n"
"    padding: 8px;")
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_4.addWidget(self.search_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.all_applications_button = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.all_applications_button.sizePolicy().hasHeightForWidth())
        self.all_applications_button.setSizePolicy(sizePolicy)
        self.all_applications_button.setMinimumSize(QtCore.QSize(0, 3))
        self.all_applications_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.all_applications_button.setStyleSheet("    border-radius: 8px;\n"
"    padding: 8px;")
        self.all_applications_button.setObjectName("all_applications_button")
        self.horizontalLayout_2.addWidget(self.all_applications_button)
        self.decision_combobox = QtWidgets.QComboBox(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decision_combobox.sizePolicy().hasHeightForWidth())
        self.decision_combobox.setSizePolicy(sizePolicy)
        self.decision_combobox.setMinimumSize(QtCore.QSize(250, 30))
        self.decision_combobox.setMaximumSize(QtCore.QSize(293, 16777215))
        self.decision_combobox.setObjectName("decision_combobox")
        self.decision_combobox.addItem("")
        self.decision_combobox.addItem("")
        self.horizontalLayout_2.addWidget(self.decision_combobox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.applications_table = QtWidgets.QTableWidget(parent=self.frame_2)
        self.applications_table.setMaximumSize(QtCore.QSize(16777215, 805))
        self.applications_table.setTabletTracking(False)
        self.applications_table.setStyleSheet("    background-color: #eaf6fb; /* veya örnek: #f0f0f0 (açık gri) */\n"
"    color: black;\n"
"    gridline-color: #005f86;\n"
"    alternate-background-color: #f9f9f9;    \n"
"\n"
"    selection-background-color: #00aaff;\n"
"    selection-color: black;\n"
"    border-radius: 0px;\n"
"")
        self.applications_table.setObjectName("applications_table")
        self.applications_table.setColumnCount(6)
        self.applications_table.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.applications_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.applications_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.applications_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.applications_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.applications_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.applications_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.applications_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.applications_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.applications_table.setItem(4, 1, item)
        self.applications_table.horizontalHeader().setDefaultSectionSize(130)
        self.applications_table.horizontalHeader().setSortIndicatorShown(False)
        self.verticalLayout_2.addWidget(self.applications_table)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.back_button = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_button.sizePolicy().hasHeightForWidth())
        self.back_button.setSizePolicy(sizePolicy)
        self.back_button.setMinimumSize(QtCore.QSize(80, 32))
        self.back_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.back_button.setStyleSheet("    border-radius: 8px;\n"
"    padding: 8px;")
        self.back_button.setObjectName("back_button")
        self.horizontalLayout_3.addWidget(self.back_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.exit_button = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_button.sizePolicy().hasHeightForWidth())
        self.exit_button.setSizePolicy(sizePolicy)
        self.exit_button.setMinimumSize(QtCore.QSize(60, 32))
        self.exit_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.exit_button.setStyleSheet("    border-radius: 8px;\n"
"    padding: 8px;")
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout_3.addWidget(self.exit_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "Mentor Meeting"))
        self.search_button.setText(_translate("MainWindow", "🔍 Search"))
        self.all_applications_button.setText(_translate("MainWindow", "🗂️ All Applications"))
        self.decision_combobox.setItemText(0, _translate("MainWindow", "VIT Projesinin Tamamına Katılması Uygun Olur"))
        self.decision_combobox.setItemText(1, _translate("MainWindow", "VIT Projesini ile IT Eğitimi Alanına Yönlendirilmesi"))
        item = self.applications_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.applications_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Görüşme Tarihi"))
        item = self.applications_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ad Soyad"))
        item = self.applications_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mentor"))
        item = self.applications_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "IT Bilgisi"))
        item = self.applications_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Yogunluk"))
        item = self.applications_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Yorumlar"))
        __sortingEnabled = self.applications_table.isSortingEnabled()
        self.applications_table.setSortingEnabled(False)
        self.applications_table.setSortingEnabled(__sortingEnabled)
        self.back_button.setText(_translate("MainWindow", "🔙 Back to Preferences"))
        self.exit_button.setText(_translate("MainWindow", "❌ Exit"))
