# Form implementation generated from reading ui file 'c:\Users\Gebruiker\Documents\GitHub\Python-Module-Week7\ui\preferences_admin.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AdminMenu(object):
    def setupUi(self, AdminMenu):
        AdminMenu.setObjectName("AdminMenu")
        AdminMenu.resize(765, 392)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AdminMenu.sizePolicy().hasHeightForWidth())
        AdminMenu.setSizePolicy(sizePolicy)
        AdminMenu.setMinimumSize(QtCore.QSize(640, 380))
        AdminMenu.setMaximumSize(QtCore.QSize(770, 500))
        AdminMenu.setStyleSheet("\n"
"background-color: rgb(85, 170, 127);\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(AdminMenu)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=AdminMenu)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #ccffcc;\n"
"    border-radius: 15px;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton {\n"
"    background-color: #55aa7f;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 20px;\n"
"    color: #b1ff00;\n"
"                }\n"
"QPushButton:hover {\n"
"    background-color: #99ff99;\n"
"    color: #55aa7f;\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: #66ff66;\n"
"}\n"
"            \n"
"\n"
"                ")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(110, 30))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("c:\\Users\\Gebruiker\\Documents\\GitHub\\Python-Module-Week7\\ui\\../resorces/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setStyleSheet("color: #006400;              /* Çok koyu yeşil: DarkGreen */\n"
"font: bold 16pt \"Segoe UI\";  /* Kalın ve 16 punto Segoe UI */\n"
"\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.btn_exit = QtWidgets.QPushButton(parent=self.frame)
        self.btn_exit.setMaximumSize(QtCore.QSize(110, 30))
        self.btn_exit.setStyleSheet("font-size: 15px;\n"
"padding: 0px;")
        self.btn_exit.setObjectName("btn_exit")
        self.horizontalLayout_2.addWidget(self.btn_exit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_admin_menu = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_admin_menu.sizePolicy().hasHeightForWidth())
        self.btn_admin_menu.setSizePolicy(sizePolicy)
        self.btn_admin_menu.setMinimumSize(QtCore.QSize(0, 100))
        self.btn_admin_menu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_admin_menu.setStyleSheet("font-size: 30px;")
        self.btn_admin_menu.setObjectName("btn_admin_menu")
        self.gridLayout.addWidget(self.btn_admin_menu, 1, 1, 1, 1)
        self.btn_mentor = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mentor.sizePolicy().hasHeightForWidth())
        self.btn_mentor.setSizePolicy(sizePolicy)
        self.btn_mentor.setMinimumSize(QtCore.QSize(0, 100))
        self.btn_mentor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_mentor.setStyleSheet("font-size: 30px;")
        self.btn_mentor.setObjectName("btn_mentor")
        self.gridLayout.addWidget(self.btn_mentor, 0, 1, 1, 1)
        self.btn_applications = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_applications.sizePolicy().hasHeightForWidth())
        self.btn_applications.setSizePolicy(sizePolicy)
        self.btn_applications.setMinimumSize(QtCore.QSize(0, 100))
        self.btn_applications.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_applications.setFont(font)
        self.btn_applications.setStyleSheet("font-size: 30px;")
        self.btn_applications.setObjectName("btn_applications")
        self.gridLayout.addWidget(self.btn_applications, 0, 0, 1, 1)
        self.btn_interviews = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_interviews.sizePolicy().hasHeightForWidth())
        self.btn_interviews.setSizePolicy(sizePolicy)
        self.btn_interviews.setMinimumSize(QtCore.QSize(0, 100))
        self.btn_interviews.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_interviews.setStyleSheet("font-size: 30px;")
        self.btn_interviews.setObjectName("btn_interviews")
        self.gridLayout.addWidget(self.btn_interviews, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(AdminMenu)
        QtCore.QMetaObject.connectSlotsByName(AdminMenu)

    def retranslateUi(self, AdminMenu):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("AdminMenu", "Preferences Menu - Admin"))
        self.btn_exit.setText(_translate("AdminMenu", "❌ Exit"))
        self.btn_admin_menu.setText(_translate("AdminMenu", "🛠️ Admin Menu"))
        self.btn_mentor.setText(_translate("AdminMenu", "👩‍🏫 Mentor Meeting"))
        self.btn_applications.setText(_translate("AdminMenu", "📦 Applications"))
        self.btn_interviews.setText(_translate("AdminMenu", "🗣️ Interviews"))
