# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dl_login(object):
    def setupUi(self, dl_login):
        dl_login.setObjectName("dl_login")
        dl_login.resize(303, 247)
        dl_login.setSizeGripEnabled(False)
        dl_login.setModal(True)
        self.checkBox = QtWidgets.QCheckBox(parent=dl_login)
        self.checkBox.setGeometry(QtCore.QRect(260, 140, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox.setFont(font)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=dl_login)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 90, 221, 145))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.lb_forget = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.lb_forget.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lb_forget.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_forget.setObjectName("lb_forget")
        self.gridLayout.addWidget(self.lb_forget, 6, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 0, 1, 1)
        self.lb_error = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.lb_error.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lb_error.setFont(font)
        self.lb_error.setText("")
        self.lb_error.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_error.setObjectName("lb_error")
        self.gridLayout.addWidget(self.lb_error, 3, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit.setToolTip("")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=dl_login)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 240, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(240, 60))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("wearhere_transparent.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(dl_login)
        QtCore.QMetaObject.connectSlotsByName(dl_login)

    def retranslateUi(self, dl_login):
        _translate = QtCore.QCoreApplication.translate
        dl_login.setWindowTitle(_translate("dl_login", "Login"))
        self.checkBox.setToolTip(_translate("dl_login", "Show password"))
        self.pushButton.setText(_translate("dl_login", "Login"))
        self.pushButton_2.setText(_translate("dl_login", "Exit"))
        self.lb_forget.setText(_translate("dl_login", "Forgot password?"))
        self.lineEdit_2.setPlaceholderText(_translate("dl_login", "password"))
        self.lineEdit.setPlaceholderText(_translate("dl_login", "username"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dl_login = QtWidgets.QDialog()
    ui = Ui_dl_login()
    ui.setupUi(dl_login)
    dl_login.show()
    sys.exit(app.exec())
